WHITESPACE = _{" " | "\n" | "\r" | "\t"}
lalpha = _{'a'..'z'}
digit = _{'0'..'9'}

tag = @{(ASCII_ALPHANUMERIC | "_" | "-")+}

//

composition = {"<<" ~ tag ~ ("," ~ tag)*}
subsumption = {"<+" ~ tag ~ ("," ~ tag)*}
instantiation = {":" ~ tag ~ ("," ~ tag)*}

aspect = {(subsumption | composition | instantiation)}

//

declaration = {tag ~ ("," ~ tag)* ~ aspect*}

ontology = {WHITESPACE* ~ declaration ~ ((";" ~ declaration) | ";")*}